<?php

/**
 * Implememnts hook_schema.
 */
function ishuman_schema() {
  $schema['ishuman_key'] = [
    'description' => 'Ensures keys only used once',
    'fields' => [
      'ihid' => [
        'type' => 'char',
        'length' => 32+14,
        'not null' => TRUE,
        'default' => '',
      ],
    ],
    'primary key' => ['ihid'],
  ];
  return $schema;
}
function ishuman_update_7100() {
  db_query('ALTER TABLE ishuman_key MODIFY ihid CHAR(46) NOT NULL');
}
